# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20160528_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 5, 28, 22, 30, 9, 819384)),
        ),
    ]
